name = "sparrowhub"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[assets]
directory = "./dist"

[env.vars]
CUSTOM_DOMAIN = "0x0e.top"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "0x0e.top"

[env.production]
name = "sparrowhub"
routes = [
  { pattern = "docker.0x0e.top", custom_domain = true },
  { pattern = "quay.0x0e.top", custom_domain = true },
  { pattern = "gcr.0x0e.top", custom_domain = true },
  { pattern = "k8s-gcr.0x0e.top", custom_domain = true },
  { pattern = "k8s.0x0e.top", custom_domain = true },
  { pattern = "ghcr.0x0e.top", custom_domain = true },
  { pattern = "cloudsmith.0x0e.top", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "sparrowhub-staging"
# route = { pattern = "docker-staging.0x0e.top", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
